import { RateLimiterMemory } from "rate-limiter-flexible"
import type { Request, Response, NextFunction } from "express"

// SAFETY MEASURES: GENERATED BY GITHUB COPILOT

// Rate limiter: 100 requests per 15 minutes per IP
const rateLimiter = new RateLimiterMemory({
  points: 200,
  duration: 15 * 60,
})

// API-specific limiter: 30 requests per 5 minutes
const apiLimiter = new RateLimiterMemory({
  points: 100,
  duration: 5 * 60,
})

export const rateLimiterMiddleware = (
  req: Request,
  res: Response,
  next: NextFunction
): void => {
  rateLimiter
    .consume(req.ip || "unknown")
    .then(() => next())
    .catch(() => {
      res.status(429).json({ error: "Too many requests. Try again later." })
    })
}

export const apiRateLimiterMiddleware = (
  req: Request,
  res: Response,
  next: NextFunction
): void => {
  apiLimiter
    .consume(req.ip || "unknown")
    .then(() => next())
    .catch(() => {
      res.status(429).json({ error: "API rate limit exceeded." })
    })
}
